LARGE_DIR=checkpoints/cased_L-24_H-1024_A-16/xlnet_cased_L-24_H-1024_A-16
GLUE_DIR=glue_data
TASK="CoLA"
TASK_NAME=`echo $TASK | awk '{print tolower($0)}'`
PRED_DIR=pred/$TASK
WORK=${1:-"eval"}
STEP=${2:-600}
if [ $WORK = "test" ]; then
CUDA_VISIBLE_DEVICES=0 python run_classifier.py \
  --do_train=False \
  --do_predict=True \
  --eval_split=test \
  --predict_dir=$PRED_DIR \
  --predict_ckpt=exp/$TASK_NAME/model.ckpt-$STEP \
  --task_name=$TASK_NAME \
  --data_dir=${GLUE_DIR}/$TASK \
  --output_dir=proc_data/$TASK_NAME \
  --model_dir=exp/$TASK_NAME \
  --uncased=False \
  --spiece_model_file=${LARGE_DIR}/spiece.model \
  --model_config_path=${LARGE_DIR}/model_config.json \
  --max_seq_length=64 \
  --eval_batch_size=8 \
  --num_hosts=1 \
  --num_core_per_host=1
#   --eval_all_ckpt=True \
#   --do_eval=True \
else
CUDA_VISIBLE_DEVICES=0 python run_classifier.py \
  --do_train=False \
  --do_eval=True \
  --task_name=$TASK_NAME \
  --data_dir=${GLUE_DIR}/$TASK \
  --output_dir=proc_data/$TASK_NAME \
  --model_dir=exp/$TASK_NAME \
  --uncased=False \
  --spiece_model_file=${LARGE_DIR}/spiece.model \
  --model_config_path=${LARGE_DIR}/model_config.json \
  --max_seq_length=64 \
  --eval_batch_size=8 \
  --num_hosts=1 \
  --eval_all_ckpt=True \
  --num_core_per_host=1
#   --do_predict=True \
#   --eval_split=test \
#   --predict_dir=$PRED_DIR \
#   --predict_ckpt=exp/$TASK_NAME/model.ckpt-600 \
#   --predict_threshold=0.5 \
fi
# Expected performance: "eval_pearsonr 0.916+ "
