LARGE_DIR=checkpoints/cased_L-24_H-1024_A-16/xlnet_cased_L-24_H-1024_A-16
GLUE_DIR=glue_data
TASK="CoLA"
TASK_NAME=`echo $TASK | awk '{print tolower($0)}'`
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python run_classifier.py \
  --do_train=True \
  --do_eval=False \
  --task_name=$TASK_NAME \
  --data_dir=${GLUE_DIR}/$TASK \
  --output_dir=proc_data/$TASK_NAME \
  --model_dir=exp/$TASK_NAME \
  --uncased=False \
  --spiece_model_file=${LARGE_DIR}/spiece.model \
  --model_config_path=${LARGE_DIR}/model_config.json \
  --init_checkpoint=${LARGE_DIR}/xlnet_model.ckpt \
  --max_seq_length=64 \
  --train_batch_size=16 \
  --num_hosts=1 \
  --num_core_per_host=8 \
  --learning_rate=3e-5 \
  --train_steps=3000 \
  --warmup_steps=500 \
  --save_steps=600 
